<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <RepositoryUrl></RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Title>Massendatenänderung OSPlus Gui</Title>
    <Product>Massendatenänderung OSPlus Gui</Product>
    <Description>Grafische Benutzeroberfläche für das Kommandozeilentool "Massendatenänderung OSPlus"
    </Description>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <Authors>Heiko Dorsch</Authors>
    <Company></Company>
    <Copyright>Heiko Dorsch</Copyright>
    <ApplicationIcon>Content\icon.ico</ApplicationIcon>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageTags>OSPlus;FI;FinanzInformatik;One-System-Plus;Massendatenänderung OSPlus</PackageTags>
    <PackageId>MassendatenänderungOSPlusGui</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\icon.ico" />
    <None Remove="Content\splash.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MassenaenderungPMSv2\MassenaenderungPMSv2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Content\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Content\splash.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="License.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
